### ISSUE TITLE
"Possible SSL connectivity problems detected."

### ISSUE THREAD

**Issue by dvg-p4** [grimbough/biomaRt#78]
Possible SSL connectivity problems detected.
Please report this issue at https://github.com/grimbough/biomaRt/issues
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Peer certificate cannot be authenticated with given CA certificates: [uswest.ensembl.org] Peer's Certificate has expired.

**Comment by grimbough** [comment]
Thank you for the report.  This was because the uswest mirror has now been retired (https://www.ensembl.info/2023/01/13/retirement-of-ensembl-us-west-aws-mirror/) and your query ended up there.  I've now updated biomaRt to remove any reference to that mirror, and hopefully this won't affect you again.
